services:

  mysql:
    image: percona:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf:/etc/my.cnf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./clickhouse/user_files:/data # Share clickhouse user files with MySQL
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
      - "9004:9004"  # MySQL interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/config:/etc/clickhouse-server/config.d
      - ./clickhouse/users:/etc/clickhouse-server/users.d
      - ./clickhouse/init:/docker-entrypoint-initdb.d
      - ./clickhouse/user_files:/var/lib/clickhouse/user_files
    environment:
      CLICKHOUSE_DB: app_db
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    networks:
      - app-network

  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html
      - ./php/config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/config/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - clickhouse
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DB: app_db
    networks:
      - app-network

volumes:
  clickhouse_data:
  mysql_data:

networks:
  app-network:
    driver: bridge
