USE app_db;

CREATE TABLE IF NOT EXISTS `general_payments` (
  `record_number` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `change_type` text COMMENT 'Change_Type',
  `covered_recipient_type` text COMMENT 'Covered_Recipient_Type',
  `teaching_hospital_ccn` text COMMENT 'Teaching_Hospital_CCN',
  `teaching_hospital_id` text COMMENT 'Teaching_Hospital_ID',
  `teaching_hospital_name` text COMMENT 'Teaching_Hospital_Name',
  `covered_recipient_profile_id` text COMMENT 'Covered_Recipient_Profile_ID',
  `covered_recipient_npi` text COMMENT 'Covered_Recipient_NPI',
  `covered_recipient_first_name` text COMMENT 'Covered_Recipient_First_Name',
  `covered_recipient_middle_name` text COMMENT 'Covered_Recipient_Middle_Name',
  `covered_recipient_last_name` text COMMENT 'Covered_Recipient_Last_Name',
  `covered_recipient_name_suffix` text COMMENT 'Covered_Recipient_Name_Suffix',
  `recipient_primary_business_street_address_line1` text COMMENT 'Recipient_Primary_Business_Street_Address_Line1',
  `recipient_primary_business_street_address_line2` text COMMENT 'Recipient_Primary_Business_Street_Address_Line2',
  `recipient_city` text COMMENT 'Recipient_City',
  `recipient_state` text COMMENT 'Recipient_State',
  `recipient_zip_code` text COMMENT 'Recipient_Zip_Code',
  `recipient_country` text COMMENT 'Recipient_Country',
  `recipient_province` text COMMENT 'Recipient_Province',
  `recipient_postal_code` text COMMENT 'Recipient_Postal_Code',
  `covered_recipient_primary_type_1` text COMMENT 'Covered_Recipient_Primary_Type_1',
  `covered_recipient_primary_type_2` text COMMENT 'Covered_Recipient_Primary_Type_2',
  `covered_recipient_primary_type_3` text COMMENT 'Covered_Recipient_Primary_Type_3',
  `covered_recipient_primary_type_4` text COMMENT 'Covered_Recipient_Primary_Type_4',
  `covered_recipient_primary_type_5` text COMMENT 'Covered_Recipient_Primary_Type_5',
  `covered_recipient_primary_type_6` text COMMENT 'Covered_Recipient_Primary_Type_6',
  `covered_recipient_specialty_1` text COMMENT 'Covered_Recipient_Specialty_1',
  `covered_recipient_specialty_2` text COMMENT 'Covered_Recipient_Specialty_2',
  `covered_recipient_specialty_3` text COMMENT 'Covered_Recipient_Specialty_3',
  `covered_recipient_specialty_4` text COMMENT 'Covered_Recipient_Specialty_4',
  `covered_recipient_specialty_5` text COMMENT 'Covered_Recipient_Specialty_5',
  `covered_recipient_specialty_6` text COMMENT 'Covered_Recipient_Specialty_6',
  `covered_recipient_license_state_code1` text COMMENT 'Covered_Recipient_License_State_code1',
  `covered_recipient_license_state_code2` text COMMENT 'Covered_Recipient_License_State_code2',
  `covered_recipient_license_state_code3` text COMMENT 'Covered_Recipient_License_State_code3',
  `covered_recipient_license_state_code4` text COMMENT 'Covered_Recipient_License_State_code4',
  `covered_recipient_license_state_code5` text COMMENT 'Covered_Recipient_License_State_code5',
  `submitting_applicable_manufacturer_or_applicable_gpo_name` text COMMENT 'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name',
  `applicable_manufacturer_or_applicable_gpo_making_payment_id` text COMMENT 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
  `applicable_manufacturer_or_applicable_gpo_making_payment_name` text COMMENT 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name',
  `applicable_manufacturer_or_applicable_gpo_making_payment_state` text COMMENT 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State',
  `applicable_manufacturer_or_applicable_gpo_making_payment_country` text COMMENT 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country',
  `total_amount_of_payment_usdollars` text COMMENT 'Total_Amount_of_Payment_USDollars',
  `date_of_payment` text COMMENT 'Date_of_Payment',
  `number_of_payments_included_in_total_amount` text COMMENT 'Number_of_Payments_Included_in_Total_Amount',
  `form_of_payment_or_transfer_of_value` text COMMENT 'Form_of_Payment_or_Transfer_of_Value',
  `nature_of_payment_or_transfer_of_value` text COMMENT 'Nature_of_Payment_or_Transfer_of_Value',
  `city_of_travel` text COMMENT 'City_of_Travel',
  `state_of_travel` text COMMENT 'State_of_Travel',
  `country_of_travel` text COMMENT 'Country_of_Travel',
  `physician_ownership_indicator` text COMMENT 'Physician_Ownership_Indicator',
  `third_party_payment_recipient_indicator` text COMMENT 'Third_Party_Payment_Recipient_Indicator',
  `name_of_third_party_entity_receiving_payment_or_transfer_of_ccfc` text COMMENT 'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value',
  `charity_indicator` text COMMENT 'Charity_Indicator',
  `third_party_equals_covered_recipient_indicator` text COMMENT 'Third_Party_Equals_Covered_Recipient_Indicator',
  `contextual_information` text COMMENT 'Contextual_Information',
  `delay_in_publication_indicator` text COMMENT 'Delay_in_Publication_Indicator',
  `record_id` text COMMENT 'Record_ID',
  `dispute_status_for_publication` text COMMENT 'Dispute_Status_for_Publication',
  `related_product_indicator` text COMMENT 'Related_Product_Indicator',
  `covered_or_noncovered_indicator_1` text COMMENT 'Covered_or_Noncovered_Indicator_1',
  `indicate_drug_or_biological_or_device_or_medical_supply_1` text COMMENT 'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1',
  `product_category_or_therapeutic_area_1` text COMMENT 'Product_Category_or_Therapeutic_Area_1',
  `name_of_drug_or_biological_or_device_or_medical_supply_1` text COMMENT 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1',
  `associated_drug_or_biological_ndc_1` text COMMENT 'Associated_Drug_or_Biological_NDC_1',
  `associated_device_or_medical_supply_pdi_1` text COMMENT 'Associated_Device_or_Medical_Supply_PDI_1',
  `covered_or_noncovered_indicator_2` text COMMENT 'Covered_or_Noncovered_Indicator_2',
  `indicate_drug_or_biological_or_device_or_medical_supply_2` text COMMENT 'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2',
  `product_category_or_therapeutic_area_2` text COMMENT 'Product_Category_or_Therapeutic_Area_2',
  `name_of_drug_or_biological_or_device_or_medical_supply_2` text COMMENT 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2',
  `associated_drug_or_biological_ndc_2` text COMMENT 'Associated_Drug_or_Biological_NDC_2',
  `associated_device_or_medical_supply_pdi_2` text COMMENT 'Associated_Device_or_Medical_Supply_PDI_2',
  `covered_or_noncovered_indicator_3` text COMMENT 'Covered_or_Noncovered_Indicator_3',
  `indicate_drug_or_biological_or_device_or_medical_supply_3` text COMMENT 'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3',
  `product_category_or_therapeutic_area_3` text COMMENT 'Product_Category_or_Therapeutic_Area_3',
  `name_of_drug_or_biological_or_device_or_medical_supply_3` text COMMENT 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3',
  `associated_drug_or_biological_ndc_3` text COMMENT 'Associated_Drug_or_Biological_NDC_3',
  `associated_device_or_medical_supply_pdi_3` text COMMENT 'Associated_Device_or_Medical_Supply_PDI_3',
  `covered_or_noncovered_indicator_4` text COMMENT 'Covered_or_Noncovered_Indicator_4',
  `indicate_drug_or_biological_or_device_or_medical_supply_4` text COMMENT 'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4',
  `product_category_or_therapeutic_area_4` text COMMENT 'Product_Category_or_Therapeutic_Area_4',
  `name_of_drug_or_biological_or_device_or_medical_supply_4` text COMMENT 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4',
  `associated_drug_or_biological_ndc_4` text COMMENT 'Associated_Drug_or_Biological_NDC_4',
  `associated_device_or_medical_supply_pdi_4` text COMMENT 'Associated_Device_or_Medical_Supply_PDI_4',
  `covered_or_noncovered_indicator_5` text COMMENT 'Covered_or_Noncovered_Indicator_5',
  `indicate_drug_or_biological_or_device_or_medical_supply_5` text COMMENT 'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5',
  `product_category_or_therapeutic_area_5` text COMMENT 'Product_Category_or_Therapeutic_Area_5',
  `name_of_drug_or_biological_or_device_or_medical_supply_5` text COMMENT 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5',
  `associated_drug_or_biological_ndc_5` text COMMENT 'Associated_Drug_or_Biological_NDC_5',
  `associated_device_or_medical_supply_pdi_5` text COMMENT 'Associated_Device_or_Medical_Supply_PDI_5',
  `program_year` text COMMENT 'Program_Year',
  `payment_publication_date` text COMMENT 'Payment_Publication_Date',
  PRIMARY KEY (`record_number`),
  KEY `idx1` (`covered_recipient_profile_id`(12),`nature_of_payment_or_transfer_of_value`(50),`submitting_applicable_manufacturer_or_applicable_gpo_name`(50)),
  KEY `idx2` (`teaching_hospital_ccn`(6),`nature_of_payment_or_transfer_of_value`(50),`submitting_applicable_manufacturer_or_applicable_gpo_name`(50)),
  KEY `idx3` (`applicable_manufacturer_or_applicable_gpo_making_payment_id`(12),`nature_of_payment_or_transfer_of_value`(50),`teaching_hospital_name`(50),`covered_recipient_first_name`(20),`covered_recipient_last_name`(20)),
  KEY `idx5` (`record_id`(12)),
  KEY `idx12` (`covered_recipient_profile_id`(10)),
  KEY `idx14` (`applicable_manufacturer_or_applicable_gpo_making_payment_id`(20)),
  KEY `idx22` (`recipient_state`(2),`covered_recipient_type`(75))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;